# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerid', models.IntegerField()),
                ('type', models.IntegerField()),
                ('object_id', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=320)),
                ('userid', models.IntegerField()),
                ('addtime', models.CharField(max_length=30)),
                ('uptime', models.CharField(max_length=30)),
                ('orderid', models.IntegerField()),
                ('cateid', models.IntegerField()),
                ('count_click', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Moview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField()),
                ('title', models.CharField(max_length=120)),
                ('de', models.CharField(max_length=150)),
                ('pid', models.IntegerField()),
                ('publish_time', models.IntegerField()),
                ('like_num', models.IntegerField()),
                ('share_num', models.IntegerField()),
                ('post_type', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
                ('request_url', models.CharField(max_length=100)),
                ('ispromote', models.IntegerField()),
                ('isalbum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernmae', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='media')),
                ('userToken', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Moview'),
        ),
        migrations.AddField(
            model_name='like',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.User'),
        ),
    ]
